version: '2'

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
      - image: expert360/elasticmq

    steps:
      - checkout

      - restore_cache:
          key: v3-sqs-utils-{{ arch }}-{{ checksum "project.clj" }}

      - run:
          name: Install dependencies
          command: lein deps

      - save_cache:
          key: v3-sqs-utils-{{ arch }}-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - run:
          name: Run tests
          command: lein test :all

      - store_test_results:
          path: ~/test_output

      - run:
          name: Create codox docs
          run: lein codox

      - store_artifacts:
          path: target/default/doc

      - deploy:
          name: Deploy jar to S3 repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                lein deploy private
            fi

      - deploy:
          name: Publish to Clojars
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                lein deploy releases
            fi
