version: '2'

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
      - image: expert360/elasticmq

    steps:
      - checkout

      - restore_cache:
          key: v1-sqs-utils-{{ arch }}-{{ checksum "project.clj" }}

      - run:
          name: Install dependencies
          command: lein deps

      - run:
          name: Install ant
          command: |
            if [ ! -d "${HOME}/ant" ]
            then
                curl -o ${HOME}/ant.tar.bz2 http://mirror.csclub.uwaterloo.ca/apache//ant/binaries/apache-ant-1.10.2-bin.tar.bz2
                tar jxf ${HOME}/ant.tar.bz2 -C ${HOME}
                mv ${HOME}/apache-ant-1.10.2 ${HOME}/ant
            fi

      - save_cache:
          key: v1-sqs-utils-{{ arch }}-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
            - ~/ant

      - run:
          name: Run tests
          command: |
            mkdir -p ~/test_output
            mkdir -p ~/artifacts
            mkdir -p ~/codox
            scripts/run_ci.sh

      - store_test_results:
          path: ~/test_output

      - store_artifacts:
          path: ~/artifacts

      - store_artifacts:
          path: ~/codox

      - deploy:
          name: Deploy jar to S3 repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                lein deploy private
            fi
